### ISSUE TITLE
$(call inherit-product-if-exists, vendor/lineage/pixel/config/common.mk

### ISSUE THREAD

**Issue by Lromdev** [Evolution-XYZ/vendor_evolution#1]
vendor/lineage/config/common.mk:10: error: unterminated call to function 'call': missing ')'.
17:16:35 dumpvars failed with: exit status 1

Forgot the symbol )

# GMS
WITH_GMS ?= true
ifeq ($(WITH_GMS),true)
$(call inherit-product-if-exists, vendor/lineage/pixel/config/common.mk
endif

# GMS
WITH_GMS ?= true
ifeq ($(WITH_GMS),true)
$(call inherit-product-if-exists, vendor/lineage/pixel/config/common.mk)
endif

**Comment by joeyhuab** [comment]
Already fixed.
